### ISSUE TITLE
Little addition in console program necessary

### ISSUE THREAD

**Issue by Marsmanni** [DevEddy/HomematicIp#6]
As the constructors in HomematicService where changed, an addition for ClientCharacteristics is needed in ConfigureServices (Line 33), else after authorization, errors are thrown:

                .AddTransient<ClientWebSocket>()
                .AddTransient<HomematicServiceBase.ClientCharacteristics>()
                .AddTransient<Func<HttpClient>>(provider => () => new HttpClient());

Everything else works really fine, I can read my thermostates!

**Comment by DevEddy** [comment]
Hi and thanks! :-)
